### ISSUE TITLE
The project Error

### ISSUE THREAD

**Issue by yorkyun** [tomlooman/SimpleFPSTemplate#5]
The project name  is  SimpleFPSTemplate ,while when i download ,it is another project named FPSGame. And the project can not generate VS project file ,also can't open

**Comment by mengzhishanghun** [comment]
#include "AI/Navigation/NavigationSystem.h"
fatal error C1083: ????????????: ??AI/Navigation/NavigationSystem.h??: No such file or directory

**Comment by mengzhishanghun** [comment]
I'm using the latest version    UE4.20.1

**Comment by pintodragon** [comment]
@mengzhishanghun You should run https://epicgames.app.box.com/s/537wc3x95udak7uqq8wja19fyvbgz7ck against the project. It will tell you what you need to udpate to make the project work.
