### ISSUE TITLE
Incompatible with latest engine v4.21.2

### ISSUE THREAD

**Issue by janissimsons** [tomlooman/SimpleFPSTemplate#8]
I downloaded your project and followed the first few videos and your code makes the project files corrupt, which causes the editor to crash.
I replicated it again by downloading fresh project files and adding only a single class: FPSObjectiveActor.cpp

Here is the code for this class:
**header:** https://gist.github.com/janissimsons/6a618b37dcc14cff0c6af02ea2859525
**.cpp:** https://gist.github.com/janissimsons/33b48619880b313eeca49cf59aae24e0

After compiling the project, editor keeps crashing no matter how many times you restart it.

**Comment by tomlooman** [comment]
Assuming you're following the Udemy Course, any issues are best posted to the Q&A board there. Important also to include the specific crash message or it's impossible to track down. Cheers!
